# validate this file:
#   curl --data-binary @.codecov.yml https://codecov.io/validate

coverage:
  range: "50...85"
  round: nearest
  precision: 2
  status:
    project:
      default: false
      ccf:
        target: 70%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

